number_of_tasks=(12)
number_of_hours=(1.5)
Course_name=('Python')
Time_for_one_task=(number_of_hours/number_of_tasks)
print('Курс',Course_name ,'всего задач',number_of_tasks ,'затрачено часов',number_of_hours ,'среднее время выполнения',Time_for_one_task)